import { StyleSheet } from 'react-native';
export const styles = StyleSheet.create({
  secao: { fontSize: 18, fontWeight: '600', marginTop: 4 },
  atalhos: { flexDirection: 'row', alignItems: 'stretch', gap: 8 },
  atalho: {
    flex: 1,
    minWidth: 0,
    alignItems: 'center',
    gap: 12,
    borderWidth: 1,
    borderRadius: 20,
    paddingVertical: 16,
    paddingHorizontal: 6,
    minHeight: 152,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.035,
    shadowRadius: 10,
    elevation: 1,
  },
  icone: {
    width: 44,
    height: 44,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  textoAtalho: { width: '100%', alignItems: 'center', gap: 5 },
  tituloAtalho: { fontSize: 12, fontWeight: '700', lineHeight: 18, textAlign: 'center' },
  descricaoAtalho: { fontSize: 11, lineHeight: 16, textAlign: 'center' },
  titulo: { fontSize: 15, fontWeight: '700', lineHeight: 21 },
  descricao: { fontSize: 12, lineHeight: 18, marginTop: 4 },
  informacao: { padding: 14, borderRadius: 18, gap: 8 },
  informacaoTitulo: { flexDirection: 'row', alignItems: 'center', gap: 8 },
});
