import { StyleSheet } from 'react-native';

export const s = StyleSheet.create({
  heroTopo: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 18,
  },
  heroEmblema: {
    width: 46,
    height: 46,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.22)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.35)',
  },
  heroArco: {
    position: 'absolute',
    width: 320,
    height: 320,
    borderRadius: 160,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.25)',
    right: -120,
    bottom: -170,
  },
  acaoConteudo: { gap: 5, flex: 1, minWidth: 0 },
  acaoDescricao: { fontSize: 12, lineHeight: 18 },
  acaoLarga: { width: '100%', flexDirection: 'row', alignItems: 'center', minHeight: 84 },

  cabecalhoAzul: { borderBottomLeftRadius: 24, borderBottomRightRadius: 24, marginBottom: 12 },
  cabecalhoArcoExterno: {
    position: 'absolute',
    width: 300,
    height: 300,
    borderRadius: 150,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.10)',
    right: -60,
    top: -120,
  },
  cabecalhoArcoInterno: {
    position: 'absolute',
    width: 230,
    height: 230,
    borderRadius: 115,
    backgroundColor: 'rgba(255,255,255,0.035)',
    right: -25,
    top: -85,
  },
  sosCardContainer: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 20,
    paddingHorizontal: 16,
    marginBottom: 26,
    borderRadius: 28,
    borderWidth: 1.5,
    shadowColor: '#FF2D55',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 3,
  },
  sosCardTopo: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
  },
  sosBadgeAlerta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 5,
    paddingHorizontal: 14,
    borderRadius: 20,
  },
  sosBadgeTexto: {
    flexShrink: 1,
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1.2,
  },
  sosAnelExterno: {
    width: 204,
    height: 204,
    borderRadius: 102,
    borderWidth: 2,
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 10,
  },
  sosAnelMedio: {
    width: 180,
    height: 180,
    borderRadius: 90,
    borderWidth: 3,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sosBotaoRedondo: {
    width: 156,
    height: 156,
    borderRadius: 78,
    overflow: 'hidden',
    shadowColor: '#FF2D55',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.38,
    shadowRadius: 16,
    elevation: 8,
  },
  sosGradiente: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  sosTituloRedondo: {
    fontSize: 27,
    fontWeight: '900',
    letterSpacing: 2,
    color: '#FFFFFF',
    marginTop: 2,
    marginBottom: 4,
    textAlign: 'center',
  },
  sosPillBadge: {
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.35)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sosPillText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.8,
    textAlign: 'center',
  },
  sosTextosBox: {
    alignItems: 'center',
    paddingHorizontal: 12,
    marginTop: 8,
  },
  sosTituloChamada: {
    fontSize: 17,
    fontWeight: '800',
    letterSpacing: 0.3,
    textAlign: 'center',
    marginBottom: 4,
  },
  sosSubtituloChamada: {
    fontSize: 13,
    lineHeight: 18,
    textAlign: 'center',
    maxWidth: 320,
  },
  sosBotoesRapidos: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 16,
    width: '100%',
  },
  sosBotaoLinha: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    paddingVertical: 11,
    paddingHorizontal: 8,
    borderRadius: 14,
    borderWidth: 1,
  },
  sosBotaoLinhaTexto: {
    flexShrink: 1,
    textAlign: 'center',
    fontSize: 12,
    fontWeight: '800',
  },
  sos: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 18,
    borderRadius: 22,
    marginBottom: 28,
    minHeight: 90,
  },
  sosIcone: {
    width: 44,
    height: 44,
    borderRadius: 15,
    backgroundColor: 'rgba(255,255,255,0.14)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sosTitulo: { fontSize: 18, fontWeight: '700', lineHeight: 24 },
  sosDescricao: { fontSize: 12, lineHeight: 19, marginTop: 4 },
  grupo: { marginBottom: 24 },
  grupoTitulo: { fontSize: 16, fontWeight: '600' },

  cabecalho: {
    width: '100%',
    overflow: 'hidden',
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 14,
  },
  cabecalhoConteudo: {
    width: '100%',
    maxWidth: 720,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  voltar: {
    width: 44,
    height: 44,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatar: {
    width: 46,
    height: 46,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
  },
  inicial: { fontSize: 21, fontWeight: '700' },
  usuario: { flex: 1, minWidth: 0 },
  saudacao: { fontSize: 11, lineHeight: 18 },
  nome: { fontSize: 20, lineHeight: 26, fontWeight: '600', letterSpacing: -0.7, marginTop: 2 },
  marca: { color: '#FFFFFF', fontSize: 20, fontWeight: '800', letterSpacing: -1.5 },
  marcaPonto: { color: '#FFD5E7' },
  menuFundo: { width: '100%', paddingHorizontal: 12, paddingTop: 8 },
  menu: {
    flexDirection: 'row',
    width: '100%',
    maxWidth: 720,
    alignSelf: 'center',
    padding: 6,
    borderWidth: 1,
    borderRadius: 24,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 16,
    elevation: 2,
  },
  menuItem: {
    flex: 1,
    minWidth: 0,
    minHeight: 54,
    paddingVertical: 8,
    paddingHorizontal: 2,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    borderRadius: 18,
  },
  menuTexto: { fontSize: 10, textAlign: 'center', flexShrink: 1 },
  boasVindas: {
    width: '100%',
    maxWidth: 720,
    alignSelf: 'center',
    borderRadius: 28,
    padding: 24,
    overflow: 'hidden',
    marginBottom: 16,
  },
  circulo: {
    position: 'absolute',
    width: 240,
    height: 240,
    borderRadius: 120,
    borderWidth: 38,
    borderColor: 'rgba(255,255,255,0.045)',
    right: -90,
    top: -55,
  },
  selo: { flexDirection: 'row', alignItems: 'center', gap: 7, flexShrink: 1 },
  seloTexto: {
    flexShrink: 1,
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '600',
    letterSpacing: 0.5,
  },
  titulo: { color: '#FFFFFF', fontSize: 30, lineHeight: 36, fontWeight: '700', letterSpacing: -1 },
  descricao: { color: '#FFFFFF', fontSize: 14, lineHeight: 22, marginTop: 12, maxWidth: 320 },
  assinatura: { flexDirection: 'row', alignItems: 'center', gap: 7, marginTop: 18 },
  assinaturaTexto: { flexShrink: 1, color: '#FFFFFF', fontSize: 12 },
  acoes: { width: '100%', maxWidth: 720, alignSelf: 'center' },
  secao: { marginBottom: 16, gap: 4 },
  secaoTitulo: { fontSize: 19, fontWeight: '700', letterSpacing: -0.4 },
  secaoLegenda: { fontSize: 12 },
  grade: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', rowGap: 12 },
  acao: {
    width: '48.3%',
    minHeight: 146,
    padding: 16,
    borderWidth: 1,
    borderRadius: 24,
    gap: 16,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.025,
    shadowRadius: 12,
    elevation: 1,
  },
  acaoTopo: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  icone: {
    width: 40,
    height: 40,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  acaoTexto: { fontSize: 14, fontWeight: '600', lineHeight: 20 },
  apoio: {
    width: '100%',
    maxWidth: 720,
    alignSelf: 'center',
    padding: 20,
    borderRadius: 22,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginTop: 24,
    marginBottom: 12,
  },
  apoioTitulo: { fontSize: 13, fontWeight: '600' },
  apoioDescricao: { fontSize: 11, marginTop: 5 },
  telefone: { fontSize: 25, fontWeight: '700' },
});
