import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    width: '100%',
    overflow: 'hidden',
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    marginBottom: 12,
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 14,
  },
  conteudo: {
    width: '100%',
    maxWidth: 712,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  topo: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    minHeight: 40,
    marginBottom: 18,
    gap: 8,
  },
  marcaGrupo: { flexDirection: 'row', alignItems: 'center', gap: 12, flexShrink: 1 },
  marca: { color: '#FFFFFF', fontSize: 20, fontWeight: '800', letterSpacing: -1.5 },
  ponto: { color: '#8DCFE2' },
  divisor: { height: 17, width: 1, backgroundColor: 'rgba(255,255,255,0.25)' },
  assinatura: { color: 'rgba(255,255,255,0.85)', fontSize: 10, letterSpacing: 0.4, flexShrink: 1 },
  voltar: {
    width: 40,
    height: 40,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.16)',
  },
  pressionado: { opacity: 0.65 },
  apresentacao: { flexDirection: 'row', alignItems: 'center', gap: 16 },
  textos: { flex: 1, minWidth: 0 },
  boasVindas: { color: 'rgba(255,255,255,0.85)', fontSize: 12, lineHeight: 19 },
  nome: {
    color: '#FFFFFF',
    fontSize: 20,
    lineHeight: 26,
    fontWeight: '600',
    letterSpacing: -0.7,
    marginTop: 2,
  },
  perfil: { flexDirection: 'row', gap: 6, alignItems: 'center', marginTop: 8 },
  perfilTexto: { color: 'rgba(255,255,255,0.85)', fontSize: 11 },
  avatarBorda: {
    width: 48,
    height: 48,
    borderRadius: 17,
    padding: 4,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.35)',
  },
  avatar: { flex: 1, borderRadius: 13, alignItems: 'center', justifyContent: 'center' },
  inicial: { color: '#FFFFFF', fontSize: 21, fontWeight: '500' },
  avatarDetalhe: {
    position: 'absolute',
    right: -3,
    bottom: -3,
    width: 23,
    height: 23,
    borderRadius: 9,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  arcoExterno: {
    position: 'absolute',
    width: 300,
    height: 300,
    borderRadius: 150,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.10)',
    right: -60,
    top: -120,
  },
  arcoInterno: {
    position: 'absolute',
    width: 230,
    height: 230,
    borderRadius: 115,
    backgroundColor: 'rgba(255,255,255,0.035)',
    right: -25,
    top: -85,
  },
});
