import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  wrapper: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 12,
    marginBottom: 8,
  },
  outerRing: {
    width: 204,
    height: 204,
    borderRadius: 102,
    borderWidth: 2,
    borderColor: 'rgba(58, 126, 148, 0.28)',
    backgroundColor: 'rgba(58, 126, 148, 0.08)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  middleRing: {
    width: 180,
    height: 180,
    borderRadius: 90,
    borderWidth: 3,
    borderColor: 'rgba(58, 126, 148, 0.45)',
    backgroundColor: 'rgba(58, 126, 148, 0.18)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  outerButton: {
    width: 156,
    height: 156,
    borderRadius: 78,
    overflow: 'hidden',
    shadowColor: '#143845',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 16,
    elevation: 8,
  },
  outerButtonPressed: {
    opacity: 0.92,
    transform: [{ scale: 0.95 }],
  },
  innerButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  title: {
    marginTop: 2,
    marginBottom: 4,
    color: '#FFFFFF',
    fontSize: 27,
    fontWeight: '900',
    letterSpacing: 1.5,
    lineHeight: 32,
    textAlign: 'center',
    includeFontPadding: false,
  },
  badge: {
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.35)',
    alignItems: 'center',
    justifyContent: 'center',
    maxWidth: 120,
  },
  badgeText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.8,
    includeFontPadding: false,
    textAlign: 'center',
  },
});
