import { StyleSheet } from 'react-native';
import { radius, spacing } from '@/styles/tokens';

export const styles = StyleSheet.create({
  introRegistroLocal: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    padding: 15,
    borderRadius: 19,
    borderWidth: 1,
    backgroundColor: 'rgba(255,255,255,0.65)',
  },
  introIcone: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  introTitulo: { fontSize: 15, lineHeight: 21, fontWeight: '700' },
  secaoTitulo: {
    marginTop: 10,
    fontSize: 20,
    lineHeight: 27,
    fontWeight: '700',
    letterSpacing: -0.4,
  },
  campoMensagem: { minHeight: 118, paddingTop: 14, lineHeight: 22 },
  contador: { marginTop: -7, alignSelf: 'flex-end', fontSize: 11 },
  acoesMidia: { flexDirection: 'row', flexWrap: 'wrap', gap: 9 },
  acaoMidia: {
    flexBasis: 150,
    flexGrow: 1,
    flexShrink: 1,
    minHeight: 53,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 11,
    paddingVertical: 9,
    borderRadius: 15,
  },
  acaoMidiaTexto: { flex: 1, fontSize: 12, lineHeight: 17, fontWeight: '600' },
  rotuloAnexo: { fontSize: 14, lineHeight: 20, fontWeight: '700' },
  listaAnexos: { gap: 10 },
  anexo: { overflow: 'hidden', borderWidth: 1, borderRadius: 18 },
  preview: { width: '100%', height: 190, backgroundColor: '#F9EDF4' },
  previewErro: { alignItems: 'center', justifyContent: 'center', gap: 8, padding: 16 },
  previewErroTexto: { fontSize: 12, lineHeight: 18, textAlign: 'center', fontWeight: '600' },
  videoPreview: { width: '100%', height: 210, backgroundColor: '#201D29' },
  audioPreview: {
    minHeight: 86,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 16,
  },
  audioTitulo: { fontSize: 14, lineHeight: 20, fontWeight: '700' },
  anexoInfo: { padding: 13, gap: 5 },
  anexoNomeLinha: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  anexoNome: { flex: 1, fontSize: 13, lineHeight: 19, fontWeight: '600' },
  anexoMeta: { fontSize: 12, lineHeight: 18 },
  removerAnexo: {
    minHeight: 42,
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    gap: 6,
    paddingRight: 12,
  },
  removerAnexoTexto: { fontSize: 12, fontWeight: '700' },
  privacidade: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    padding: 13,
    borderRadius: 16,
  },
  privacidadeTexto: { flex: 1, fontSize: 12, lineHeight: 19 },
  registroTopo: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  registroTitulo: { flexShrink: 1, fontSize: 16, lineHeight: 22, fontWeight: '700' },
  registroMensagem: { fontSize: 15, lineHeight: 23 },
  linhaBotoes: { flexDirection: 'column', gap: 8 },
  secoes: { marginTop: spacing.md },
});
