import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  tela: { flex: 1 },
  area: { flex: 1, width: '100%', maxWidth: 960, alignSelf: 'center' },
  topo: { flexDirection: 'row', alignItems: 'center', gap: 12, padding: 18, borderBottomWidth: 1 },
  voltar: { padding: 10, borderRadius: 14 },
  titulo: { fontSize: 23, fontWeight: '700' },
  subtitulo: { fontSize: 12, lineHeight: 18, marginTop: 3 },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  inicial: { fontSize: 19, fontWeight: '700' },
  contatos: { maxHeight: 94, borderBottomWidth: 1 },
  listaContatos: { gap: 10, padding: 14 },
  contato: {
    flexDirection: 'row',
    gap: 9,
    alignItems: 'center',
    borderWidth: 1,
    borderRadius: 18,
    padding: 10,
  },
  nome: { fontSize: 14, fontWeight: '700' },
  corpo: { flex: 1 },
  mensagens: { padding: 18, gap: 12, flexGrow: 1 },
  bolha: { maxWidth: '84%', padding: 13, borderRadius: 19, gap: 6 },
  texto: { fontSize: 15, lineHeight: 22 },
  hora: { fontSize: 10, alignSelf: 'flex-end' },
  vazio: {
    flex: 1,
    minHeight: 220,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 13,
    padding: 24,
  },
  vazioTitulo: { fontSize: 19, fontWeight: '700', textAlign: 'center' },
  vazioTexto: { fontSize: 14, lineHeight: 22, textAlign: 'center', maxWidth: 400 },
  rodape: { borderTopWidth: 1, padding: 14, gap: 9 },
  compositor: { flexDirection: 'row', alignItems: 'flex-end', gap: 10 },
  campo: {
    flex: 1,
    borderWidth: 1,
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 12,
    minHeight: 48,
    maxHeight: 130,
    fontSize: 15,
  },
  enviar: {
    width: 48,
    height: 48,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
  },
  aviso: {
    paddingHorizontal: 18,
    paddingVertical: 9,
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
  },
  avisoTexto: { flex: 1, fontSize: 12, lineHeight: 18 },
  erro: { fontSize: 13, lineHeight: 19 },
});
