import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  aviso: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    padding: 15,
    borderWidth: 1,
    borderRadius: 18,
  },
  avisoTexto: { flex: 1, fontSize: 13, lineHeight: 20, fontWeight: '600' },
  secao: { marginTop: 10, fontSize: 19, lineHeight: 26, fontWeight: '700', letterSpacing: -0.25 },
  subtituloSecao: { marginTop: -10, fontSize: 13, lineHeight: 19 },
  cardTitulo: { fontSize: 16, lineHeight: 22, fontWeight: '700' },
  ligar180: {
    minHeight: 68,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 13,
    borderWidth: 1,
    borderRadius: 18,
  },
  ligarTitulo: { fontSize: 14, fontWeight: '700' },
  ligarDescricao: { marginTop: 3, fontSize: 12, lineHeight: 17 },
  topicos: { gap: 10 },
  topico: { borderWidth: 1, borderRadius: 18, overflow: 'hidden' },
  topicoCabecalho: {
    minHeight: 66,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
    paddingHorizontal: 13,
    paddingVertical: 10,
  },
  topicoIcone: {
    width: 38,
    height: 38,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
  },
  topicoTitulo: { flex: 1, fontSize: 14, lineHeight: 20, fontWeight: '650' },
  topicoCorpo: { paddingHorizontal: 16, paddingBottom: 16, fontSize: 13, lineHeight: 21 },
  servicos: { gap: 10 },
  servico: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 11,
    padding: 14,
    borderWidth: 1,
    borderRadius: 18,
  },
  servicoIcone: {
    width: 38,
    height: 38,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
  },
  servicoTexto: { flex: 1, gap: 5 },
  servicoTitulo: { fontSize: 14, lineHeight: 20, fontWeight: '700' },
  servicoDescricao: { fontSize: 12, lineHeight: 19 },
  servicoAcao: { marginTop: 2, fontSize: 12, fontWeight: '700' },
});
